/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Work Order API
 * OpenAPI spec version: 0.1.0
 */
import { createMutation, createQuery } from "@tanstack/svelte-query";
import type {
	CreateMutationOptions,
	CreateMutationResult,
	CreateQueryOptions,
	CreateQueryResult,
	DataTag,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
} from "@tanstack/svelte-query";

import type {
	AuthResponse,
	GetMeApiV1AuthMeGet200,
	HTTPValidationError,
	HealthCheckHealthGet200,
	MessageResponse,
	RootGet200,
	TokenRefresh,
	UserSignIn,
	UserSignUp,
} from "./schemas";

import { clientWrapper } from "./client-wrapper";
/**
 * Register a new user.
 * @summary Sign Up
 */
export const signUpApiV1AuthSignupPost = (
	userSignUp: UserSignUp,
	signal?: AbortSignal,
) => {
	return clientWrapper<AuthResponse>({
		url: "/api/v1/auth/signup",
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: userSignUp,
		signal,
	});
};

export const getSignUpApiV1AuthSignupPostMutationOptions = <
	TError = HTTPValidationError,
	TContext = unknown,
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof signUpApiV1AuthSignupPost>>,
		TError,
		{ data: UserSignUp },
		TContext
	>;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof signUpApiV1AuthSignupPost>>,
	TError,
	{ data: UserSignUp },
	TContext
> => {
	const mutationKey = ["signUpApiV1AuthSignupPost"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof signUpApiV1AuthSignupPost>>,
		{ data: UserSignUp }
	> = (props) => {
		const { data } = props ?? {};

		return signUpApiV1AuthSignupPost(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type SignUpApiV1AuthSignupPostMutationResult = NonNullable<
	Awaited<ReturnType<typeof signUpApiV1AuthSignupPost>>
>;
export type SignUpApiV1AuthSignupPostMutationBody = UserSignUp;
export type SignUpApiV1AuthSignupPostMutationError = HTTPValidationError;

/**
 * @summary Sign Up
 */
export const createSignUpApiV1AuthSignupPost = <
	TError = HTTPValidationError,
	TContext = unknown,
>(
	options?: {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof signUpApiV1AuthSignupPost>>,
			TError,
			{ data: UserSignUp },
			TContext
		>;
	},
	queryClient?: QueryClient,
): CreateMutationResult<
	Awaited<ReturnType<typeof signUpApiV1AuthSignupPost>>,
	TError,
	{ data: UserSignUp },
	TContext
> => {
	const mutationOptions = getSignUpApiV1AuthSignupPostMutationOptions(options);

	return createMutation(mutationOptions, queryClient);
};

/**
 * Sign in an existing user.
 * @summary Sign In
 */
export const signInApiV1AuthSigninPost = (
	userSignIn: UserSignIn,
	signal?: AbortSignal,
) => {
	return clientWrapper<AuthResponse>({
		url: "/api/v1/auth/signin",
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: userSignIn,
		signal,
	});
};

export const getSignInApiV1AuthSigninPostMutationOptions = <
	TError = HTTPValidationError,
	TContext = unknown,
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof signInApiV1AuthSigninPost>>,
		TError,
		{ data: UserSignIn },
		TContext
	>;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof signInApiV1AuthSigninPost>>,
	TError,
	{ data: UserSignIn },
	TContext
> => {
	const mutationKey = ["signInApiV1AuthSigninPost"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof signInApiV1AuthSigninPost>>,
		{ data: UserSignIn }
	> = (props) => {
		const { data } = props ?? {};

		return signInApiV1AuthSigninPost(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type SignInApiV1AuthSigninPostMutationResult = NonNullable<
	Awaited<ReturnType<typeof signInApiV1AuthSigninPost>>
>;
export type SignInApiV1AuthSigninPostMutationBody = UserSignIn;
export type SignInApiV1AuthSigninPostMutationError = HTTPValidationError;

/**
 * @summary Sign In
 */
export const createSignInApiV1AuthSigninPost = <
	TError = HTTPValidationError,
	TContext = unknown,
>(
	options?: {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof signInApiV1AuthSigninPost>>,
			TError,
			{ data: UserSignIn },
			TContext
		>;
	},
	queryClient?: QueryClient,
): CreateMutationResult<
	Awaited<ReturnType<typeof signInApiV1AuthSigninPost>>,
	TError,
	{ data: UserSignIn },
	TContext
> => {
	const mutationOptions = getSignInApiV1AuthSigninPostMutationOptions(options);

	return createMutation(mutationOptions, queryClient);
};

/**
 * Sign out the current user.
 * @summary Sign Out
 */
export const signOutApiV1AuthSignoutPost = (signal?: AbortSignal) => {
	return clientWrapper<MessageResponse>({
		url: "/api/v1/auth/signout",
		method: "POST",
		signal,
	});
};

export const getSignOutApiV1AuthSignoutPostMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof signOutApiV1AuthSignoutPost>>,
		TError,
		void,
		TContext
	>;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof signOutApiV1AuthSignoutPost>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ["signOutApiV1AuthSignoutPost"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof signOutApiV1AuthSignoutPost>>,
		void
	> = () => {
		return signOutApiV1AuthSignoutPost();
	};

	return { mutationFn, ...mutationOptions };
};

export type SignOutApiV1AuthSignoutPostMutationResult = NonNullable<
	Awaited<ReturnType<typeof signOutApiV1AuthSignoutPost>>
>;

export type SignOutApiV1AuthSignoutPostMutationError = unknown;

/**
 * @summary Sign Out
 */
export const createSignOutApiV1AuthSignoutPost = <
	TError = unknown,
	TContext = unknown,
>(
	options?: {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof signOutApiV1AuthSignoutPost>>,
			TError,
			void,
			TContext
		>;
	},
	queryClient?: QueryClient,
): CreateMutationResult<
	Awaited<ReturnType<typeof signOutApiV1AuthSignoutPost>>,
	TError,
	void,
	TContext
> => {
	const mutationOptions =
		getSignOutApiV1AuthSignoutPostMutationOptions(options);

	return createMutation(mutationOptions, queryClient);
};

/**
 * Get current user information.
 * @summary Get Me
 */
export const getMeApiV1AuthMeGet = (signal?: AbortSignal) => {
	return clientWrapper<GetMeApiV1AuthMeGet200>({
		url: "/api/v1/auth/me",
		method: "GET",
		signal,
	});
};

export const getGetMeApiV1AuthMeGetQueryKey = () => {
	return ["/api/v1/auth/me"] as const;
};

export const getGetMeApiV1AuthMeGetQueryOptions = <
	TData = Awaited<ReturnType<typeof getMeApiV1AuthMeGet>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		CreateQueryOptions<
			Awaited<ReturnType<typeof getMeApiV1AuthMeGet>>,
			TError,
			TData
		>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetMeApiV1AuthMeGetQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getMeApiV1AuthMeGet>>
	> = ({ signal }) => getMeApiV1AuthMeGet(signal);

	return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
		Awaited<ReturnType<typeof getMeApiV1AuthMeGet>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMeApiV1AuthMeGetQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMeApiV1AuthMeGet>>
>;
export type GetMeApiV1AuthMeGetQueryError = unknown;

/**
 * @summary Get Me
 */

export function createGetMeApiV1AuthMeGet<
	TData = Awaited<ReturnType<typeof getMeApiV1AuthMeGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			CreateQueryOptions<
				Awaited<ReturnType<typeof getMeApiV1AuthMeGet>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): CreateQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetMeApiV1AuthMeGetQueryOptions(options);

	const query = createQuery(queryOptions, queryClient) as CreateQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * Refresh access token.
 * @summary Refresh Token
 */
export const refreshTokenApiV1AuthRefreshPost = (
	tokenRefresh: TokenRefresh,
	signal?: AbortSignal,
) => {
	return clientWrapper<AuthResponse>({
		url: "/api/v1/auth/refresh",
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: tokenRefresh,
		signal,
	});
};

export const getRefreshTokenApiV1AuthRefreshPostMutationOptions = <
	TError = HTTPValidationError,
	TContext = unknown,
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof refreshTokenApiV1AuthRefreshPost>>,
		TError,
		{ data: TokenRefresh },
		TContext
	>;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof refreshTokenApiV1AuthRefreshPost>>,
	TError,
	{ data: TokenRefresh },
	TContext
> => {
	const mutationKey = ["refreshTokenApiV1AuthRefreshPost"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof refreshTokenApiV1AuthRefreshPost>>,
		{ data: TokenRefresh }
	> = (props) => {
		const { data } = props ?? {};

		return refreshTokenApiV1AuthRefreshPost(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type RefreshTokenApiV1AuthRefreshPostMutationResult = NonNullable<
	Awaited<ReturnType<typeof refreshTokenApiV1AuthRefreshPost>>
>;
export type RefreshTokenApiV1AuthRefreshPostMutationBody = TokenRefresh;
export type RefreshTokenApiV1AuthRefreshPostMutationError = HTTPValidationError;

/**
 * @summary Refresh Token
 */
export const createRefreshTokenApiV1AuthRefreshPost = <
	TError = HTTPValidationError,
	TContext = unknown,
>(
	options?: {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof refreshTokenApiV1AuthRefreshPost>>,
			TError,
			{ data: TokenRefresh },
			TContext
		>;
	},
	queryClient?: QueryClient,
): CreateMutationResult<
	Awaited<ReturnType<typeof refreshTokenApiV1AuthRefreshPost>>,
	TError,
	{ data: TokenRefresh },
	TContext
> => {
	const mutationOptions =
		getRefreshTokenApiV1AuthRefreshPostMutationOptions(options);

	return createMutation(mutationOptions, queryClient);
};

/**
 * @summary Root
 */
export const rootGet = (signal?: AbortSignal) => {
	return clientWrapper<RootGet200>({ url: "/", method: "GET", signal });
};

export const getRootGetQueryKey = () => {
	return ["/"] as const;
};

export const getRootGetQueryOptions = <
	TData = Awaited<ReturnType<typeof rootGet>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		CreateQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getRootGetQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof rootGet>>> = ({
		signal,
	}) => rootGet(signal);

	return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
		Awaited<ReturnType<typeof rootGet>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RootGetQueryResult = NonNullable<
	Awaited<ReturnType<typeof rootGet>>
>;
export type RootGetQueryError = unknown;

/**
 * @summary Root
 */

export function createRootGet<
	TData = Awaited<ReturnType<typeof rootGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			CreateQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>
		>;
	},
	queryClient?: QueryClient,
): CreateQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getRootGetQueryOptions(options);

	const query = createQuery(queryOptions, queryClient) as CreateQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * @summary Health Check
 */
export const healthCheckHealthGet = (signal?: AbortSignal) => {
	return clientWrapper<HealthCheckHealthGet200>({
		url: "/health",
		method: "GET",
		signal,
	});
};

export const getHealthCheckHealthGetQueryKey = () => {
	return ["/health"] as const;
};

export const getHealthCheckHealthGetQueryOptions = <
	TData = Awaited<ReturnType<typeof healthCheckHealthGet>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		CreateQueryOptions<
			Awaited<ReturnType<typeof healthCheckHealthGet>>,
			TError,
			TData
		>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getHealthCheckHealthGetQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof healthCheckHealthGet>>
	> = ({ signal }) => healthCheckHealthGet(signal);

	return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
		Awaited<ReturnType<typeof healthCheckHealthGet>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type HealthCheckHealthGetQueryResult = NonNullable<
	Awaited<ReturnType<typeof healthCheckHealthGet>>
>;
export type HealthCheckHealthGetQueryError = unknown;

/**
 * @summary Health Check
 */

export function createHealthCheckHealthGet<
	TData = Awaited<ReturnType<typeof healthCheckHealthGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			CreateQueryOptions<
				Awaited<ReturnType<typeof healthCheckHealthGet>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): CreateQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getHealthCheckHealthGetQueryOptions(options);

	const query = createQuery(queryOptions, queryClient) as CreateQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}
