import type { BodyLoginLoginAccessTokenClientId } from "./bodyLoginLoginAccessTokenClientId";
import type { BodyLoginLoginAccessTokenClientSecret } from "./bodyLoginLoginAccessTokenClientSecret";
/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Work Order App
 * OpenAPI spec version: 0.1.0
 */
import type { BodyLoginLoginAccessTokenGrantType } from "./bodyLoginLoginAccessTokenGrantType";

export interface BodyLoginLoginAccessToken {
	grant_type?: BodyLoginLoginAccessTokenGrantType;
	username: string;
	password: string;
	scope?: string;
	client_id?: BodyLoginLoginAccessTokenClientId;
	client_secret?: BodyLoginLoginAccessTokenClientSecret;
}
