/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Work Order API
 * OpenAPI spec version: 0.1.0
 */

export type GetWorkOrdersApiV1WorkOrdersGetParams = {
	page?: number;
	limit?: number;
	status?: string | null;
	priority?: string | null;
	assigned_to?: string | null;
};
