import type { ItemUpdateDescription } from "./itemUpdateDescription";
/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Work Order App
 * OpenAPI spec version: 0.1.0
 */
import type { ItemUpdateTitle } from "./itemUpdateTitle";

export interface ItemUpdate {
	title?: ItemUpdateTitle;
	description?: ItemUpdateDescription;
}
