/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Work Order App
 * OpenAPI spec version: 0.1.0
 */
import type { ItemCreateDescription } from "./itemCreateDescription";

export interface ItemCreate {
	/**
	 * @minLength 1
	 * @maxLength 255
	 */
	title: string;
	description?: ItemCreateDescription;
}
