/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Work Order API
 * OpenAPI spec version: 0.1.0
 */
import type { LocationAddress } from "./locationAddress";
import type { LocationCity } from "./locationCity";
import type { LocationCountry } from "./locationCountry";
import type { LocationLatitude } from "./locationLatitude";
import type { LocationLongitude } from "./locationLongitude";
import type { LocationPostalCode } from "./locationPostalCode";
import type { LocationStateProvince } from "./locationStateProvince";

export interface Location {
	id: string;
	name: string;
	address?: LocationAddress;
	city?: LocationCity;
	state_province?: LocationStateProvince;
	postal_code?: LocationPostalCode;
	country?: LocationCountry;
	latitude?: LocationLatitude;
	longitude?: LocationLongitude;
}
