/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Work Order API
 * OpenAPI spec version: 0.1.0
 */
import type { LocationCreateAddress } from "./locationCreateAddress";
import type { LocationCreateCity } from "./locationCreateCity";
import type { LocationCreateLatitude } from "./locationCreateLatitude";
import type { LocationCreateLongitude } from "./locationCreateLongitude";
import type { LocationCreatePostalCode } from "./locationCreatePostalCode";
import type { LocationCreateStateProvince } from "./locationCreateStateProvince";

export interface LocationCreate {
	name: string;
	address?: LocationCreateAddress;
	city?: LocationCreateCity;
	state_province?: LocationCreateStateProvince;
	postal_code?: LocationCreatePostalCode;
	country?: string;
	latitude?: LocationCreateLatitude;
	longitude?: LocationCreateLongitude;
}
