/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Work Order App
 * OpenAPI spec version: 0.1.0
 */

export interface NewPassword {
	token: string;
	/**
	 * @minLength 8
	 * @maxLength 40
	 */
	new_password: string;
}
