/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Work Order App
 * OpenAPI spec version: 0.1.0
 */

export interface PrivateUserCreate {
	email: string;
	password: string;
	full_name: string;
	is_verified?: boolean;
}
