/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Work Order App
 * OpenAPI spec version: 0.1.0
 */
import type { UserCreateFullName } from "./userCreateFullName";

export interface UserCreate {
	/** @maxLength 255 */
	email: string;
	is_active?: boolean;
	is_superuser?: boolean;
	full_name?: UserCreateFullName;
	/**
	 * @minLength 8
	 * @maxLength 40
	 */
	password: string;
}
