import type { UserResponseEmailConfirmedAt } from "./userResponseEmailConfirmedAt";
import type { UserResponseLastSignInAt } from "./userResponseLastSignInAt";
import type { UserResponsePhone } from "./userResponsePhone";
/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Work Order API
 * OpenAPI spec version: 0.1.0
 */
import type { UserResponseUpdatedAt } from "./userResponseUpdatedAt";

export interface UserResponse {
	id: string;
	email: string;
	created_at: string;
	updated_at?: UserResponseUpdatedAt;
	email_confirmed_at?: UserResponseEmailConfirmedAt;
	phone?: UserResponsePhone;
	last_sign_in_at?: UserResponseLastSignInAt;
}
