import type { UserUpdateMeEmail } from "./userUpdateMeEmail";
/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Work Order App
 * OpenAPI spec version: 0.1.0
 */
import type { UserUpdateMeFullName } from "./userUpdateMeFullName";

export interface UserUpdateMe {
	full_name?: UserUpdateMeFullName;
	email?: UserUpdateMeEmail;
}
