/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Work Order App
 * OpenAPI spec version: 0.1.0
 */
import type { UserPublic } from "./userPublic";

export interface UsersPublic {
	data: UserPublic[];
	count: number;
}
