import type { WorkOrderCreateAssignedToUserId } from "./workOrderCreateAssignedToUserId";
/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Work Order API
 * OpenAPI spec version: 0.1.0
 */
import type { WorkOrderCreateDescription } from "./workOrderCreateDescription";
import type { WorkOrderCreateLocationId } from "./workOrderCreateLocationId";
import type { WorkOrderPriority } from "./workOrderPriority";
import type { WorkOrderStatus } from "./workOrderStatus";

export interface WorkOrderCreate {
	title: string;
	description?: WorkOrderCreateDescription;
	status?: WorkOrderStatus;
	priority?: WorkOrderPriority;
	location_id?: WorkOrderCreateLocationId;
	assigned_to_user_id?: WorkOrderCreateAssignedToUserId;
}
