/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Work Order API
 * OpenAPI spec version: 0.1.0
 */

export type WorkOrderStatus =
	(typeof WorkOrderStatus)[keyof typeof WorkOrderStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkOrderStatus = {
	Open: "Open",
	In_Progress: "In Progress",
	Completed: "Completed",
	Cancelled: "Cancelled",
	On_Hold: "On Hold",
} as const;
