/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Work Order API
 * OpenAPI spec version: 0.1.0
 */
import type { WorkOrder } from "./workOrder";
import type { WorkOrdersResponsePagination } from "./workOrdersResponsePagination";

export interface WorkOrdersResponse {
	data: WorkOrder[];
	count: number;
	pagination?: WorkOrdersResponsePagination;
}
