/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Work Order API
 * OpenAPI spec version: 0.1.0
 */
import type { PaginationInfo } from "./paginationInfo";

export type WorkOrdersResponsePagination = PaginationInfo | null;
