import type { WorkOrderAssignedToUserId } from "./workOrderAssignedToUserId";
/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Work Order API
 * OpenAPI spec version: 0.1.0
 */
import type { WorkOrderDescription } from "./workOrderDescription";
import type { WorkOrderLocation } from "./workOrderLocation";
import type { WorkOrderLocationId } from "./workOrderLocationId";
import type { WorkOrderPriority } from "./workOrderPriority";
import type { WorkOrderStatus } from "./workOrderStatus";

export interface WorkOrder {
	id: string;
	title: string;
	description?: WorkOrderDescription;
	status: WorkOrderStatus;
	priority: WorkOrderPriority;
	location?: WorkOrderLocation;
	location_id?: WorkOrderLocationId;
	assigned_to_user_id?: WorkOrderAssignedToUserId;
	created_by_user_id: string;
	created_at: string;
	updated_at: string;
}
