/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Work Order API
 * OpenAPI spec version: 0.1.0
 */

export type WorkOrderPriority =
	(typeof WorkOrderPriority)[keyof typeof WorkOrderPriority];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkOrderPriority = {
	Low: "Low",
	Medium: "Medium",
	High: "High",
} as const;
