import type { WorkOrderUpdateAssignedToUserId } from "./workOrderUpdateAssignedToUserId";
import type { WorkOrderUpdateDescription } from "./workOrderUpdateDescription";
import type { WorkOrderUpdateLocationId } from "./workOrderUpdateLocationId";
import type { WorkOrderUpdatePriority } from "./workOrderUpdatePriority";
import type { WorkOrderUpdateStatus } from "./workOrderUpdateStatus";
/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Work Order API
 * OpenAPI spec version: 0.1.0
 */
import type { WorkOrderUpdateTitle } from "./workOrderUpdateTitle";

export interface WorkOrderUpdate {
	title?: WorkOrderUpdateTitle;
	description?: WorkOrderUpdateDescription;
	status?: WorkOrderUpdateStatus;
	priority?: WorkOrderUpdatePriority;
	location_id?: WorkOrderUpdateLocationId;
	assigned_to_user_id?: WorkOrderUpdateAssignedToUserId;
}
